### ISSUE TITLE
generate-secure-pillar can't encrypt number type data

### ISSUE THREAD

**Issue by liu0013** [Everbridge/generate-secure-pillar#16]
for example, create a test.sls which include `username:123456` and then `generate-secure-pillar  encrypt all --file test.sls` that can reproduce this issue.
generate-secure-pillar version 1.0.465

**Comment by esilva-everbridge** [comment]
@liu0013 Thanks for catching this! It looks like an issue in the yamlv2 lib, but I need to dig in further to verify that.
I will update as soon as I know more.

**Comment by esilva-everbridge** [comment]
This was an issue with how value types are handled, I had assumed strings, but reflect was returning Int types, so I have updated to remove that assumption. One side effect is that values will decrypt as strings, regardless of the initial type.

The latest release has this change.
