### ISSUE TITLE
Decrypt result dose not match the original value

### ISSUE THREAD

**Issue by ansonLx** [Everbridge/generate-secure-pillar#18]
I tried to encrypt a value "F2g%r*skMW48" and then decrypt, but the result of decrypted is "F2g%!r(MISSING)\*skMW48", could you please help to look at why there are additional characters ("!" and "(MISSING)") at  the middle of decrypted value? Does this mean the GPG can't encrypt the '\*' character? Sorry about I am not very familiar with GPG encryption. Thanks.

**Comment by edlitmus** [comment]
Can you copy and paste exactly what command you used and the output? It's hard to tell what might be happening otherwise.

**Comment by ansonLx** [comment]
I used command `go build` to build the package and run the following:
`./generate-secure-pillar -k "Anson xue" encrypt all -f secretConf.yml --outfile e.yml`
then
`./generate-secure-pillar -k "Anson xue" decrypt all -f e.yml`
The attach files are my GPG keys and yml file content

[files.zip](https://github.com/Everbridge/generate-secure-pillar/files/3209880/files.zip)

**Comment by edlitmus** [comment]
@ansonLx Sorry for the delay! This turns out to be a cosmetic error when writing the value to stdout, I created a new release today (v1.0.513) that fixes it. To be clear, this didn't have any effect on writing files to disk, just to stdout.

Thanks for filing this issue!

**Comment by ansonLx** [comment]
Nice fix! Thank you @edlitmus 👍
